services:
  demo-app:
    container_name: myapp
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - "8000:8000" # 호스트 머신의 8000번 포트를 docker의 8000번 포트로 연결
    environment:
      - WATCHFILES_FORCE_POLLING=true


  db:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017" # 호스트 머신의 27017번 포트를 docker의 27017번 포트로 연결
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "27018:8081" # 호스트 머신의 27018번 포트를 docker의 8081번 포트로 연결
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_PORT=27017 # 추가: MongoDB 포트 지정

volumes:
  mongo-data: